//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prycarrito.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_CLIENTE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_CLIENTE()
        {
            this.TBL_DIRECCIONES = new HashSet<TBL_DIRECCIONES>();
            this.TBL_PEDIDO = new HashSet<TBL_PEDIDO>();
        }
    
        public long cli_id { get; set; }
        public string cli_identificacion { get; set; }
        public string cli_tipoidentificacion { get; set; }
        public string cli_apellidos { get; set; }
        public string cli_nombres { get; set; }
        public string cli_genero { get; set; }
        public System.DateTime cli_fechanacimiento { get; set; }
        public string cli_telefono { get; set; }
        public string cli_celurar { get; set; }
        public string cli_email { get; set; }
        public string cli_status { get; set; }
        public System.DateTime cli_fechacreacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_DIRECCIONES> TBL_DIRECCIONES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_PEDIDO> TBL_PEDIDO { get; set; }
    }
}
