//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prycarrito2.mvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_CATEGORIA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_CATEGORIA()
        {
            this.TBL_PRODUCTO = new HashSet<TBL_PRODUCTO>();
        }
    
        public string cat_nombre { get; set; }
        public short cat_id { get; set; }
        public string cat_descripcion { get; set; }
        public string cat_status { get; set; }
        public System.DateTime cat_fechacreacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_PRODUCTO> TBL_PRODUCTO { get; set; }
    }
}
