//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prycarrito2.mvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_PAGOS
    {
        public int pag_id { get; set; }
        public System.DateTime pag_fecha { get; set; }
        public decimal pag_valor { get; set; }
        public string pag_status { get; set; }
        public System.DateTime pag_fechacreacion { get; set; }
        public Nullable<int> ped_id { get; set; }
        public Nullable<System.DateTime> ped_fecha { get; set; }
        public Nullable<byte> fpa_id { get; set; }
    
        public virtual TBL_FORMAPAGO TBL_FORMAPAGO { get; set; }
        public virtual TBL_PEDIDO TBL_PEDIDO { get; set; }
    }
}
